= Controller
:from: v0.3.0-alpha
:icon: controller.png

The {doctitle} is the core of the Refined Storage network.
You need to connect all the Refined Storage devices to this block.

== Connecting devices

You are supposed to connect every device that depends on the storage network connection to the {doctitle}.

You can connect devices with xref:cable.adoc[cables].

xref:cable.adoc[Cables] are not always necessary, as long as the devices are next to each other in any direction a connection will be established as well.

== Energy

The {doctitle} accepts and consumes Forge Energy (FE).
Most mods have a way to generate energy, therefore Refined Storage doesn't come by itself with a way to generate energy.

- The energy is extracted per tick.
- The amount of energy that is extracted depends on the amount of devices, and which devices.
- Every device type consumes another amount of energy.
- You can see how many energy each device consumes by right clicking the {doctitle}.

If the {doctitle} runs out of energy, the network will be turned off until there is sufficient energy provided again.

When the {doctitle} is broken, it will maintain its energy.

== Limits

Each Refined Storage network can only have a single {doctitle}.
It doesn't make sense to connect multiple controllers on the same network.

If you connect another {doctitle} to an already existing network, the {doctitle} will break as an item in the world.

include::../../partials/recoloring.adoc[]